[[pages]]
path = "/"
screenshotTimestamp = "2026-04-12T01:30:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4a474e8c-b711-45fe-9561-1b1b0a7bf2d3/d55a931c-d556-4585-99fe-36b475edb134/vUWVdVw"

[[pages]]
path = "/sessions/4"
screenshotTimestamp = "2026-04-12T02:02:29Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4a474e8c-b711-45fe-9561-1b1b0a7bf2d3/d55a931c-d556-4585-99fe-36b475edb134/vMJ3Rlx"

[[pages]]
path = "/sessions"
screenshotTimestamp = "2026-04-12T02:26:48Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4a474e8c-b711-45fe-9561-1b1b0a7bf2d3/d55a931c-d556-4585-99fe-36b475edb134/Elcp8kV"
